import Link from 'next/link'
import { requireRole } from '@/lib/auth/guards'
import { resolveEdition } from '@/lib/edition/context'
import { listBatches } from '@/lib/query/payments'
import { formatNaira } from '@/lib/format/money'

export default async function PaymentsPage({
  searchParams,
}: {
  searchParams: Promise<{ edition?: string }>
}) {
  await requireRole(['admin', 'editor'])
  const { edition: editionIdParam } = await searchParams
  const edition = await resolveEdition(editionIdParam)

  if (!edition) {
    return (
      <main>
        <h1>Payments</h1>
        <p>No active edition yet.</p>
      </main>
    )
  }

  const batches = await listBatches(edition.id)

  return (
    <main>
      <h1>Payments — {edition.name}</h1>

      {batches.length === 0 ? (
        <p>No payment batches yet. Generate one from a filtered participant list.</p>
      ) : (
        <table>
          <thead>
            <tr>
              <th scope="col">Reference</th>
              <th scope="col">Date</th>
              <th scope="col">Records</th>
              <th scope="col">Total</th>
              <th scope="col">Status</th>
              <th scope="col">Generated by</th>
            </tr>
          </thead>
          <tbody>
            {batches.map((batch) => (
              <tr key={batch.id}>
                <td>
                  <Link href={`/payments/${batch.id}`}>{batch.reference}</Link>
                </td>
                <td>{new Date(batch.generatedAt).toLocaleString()}</td>
                <td>{batch.recordCount}</td>
                <td>{formatNaira(batch.totalAmount)}</td>
                <td>{batch.status}</td>
                <td>{batch.generatedByName}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </main>
  )
}
