// Generated by scripts/_gen-types-introspect.mjs via direct information_schema
// introspection (Docker and a Supabase personal access token were both
// unavailable in the environment that generated this). Regenerate with
// `npm run db:types` once either is available — see docs/infrastructure.md.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      "access_logs": {
        Row: {
          "id": number
          "user_id": string | null
          "role": string | null
          "route": string
          "action": string
          "edition_id": string | null
          "filters": Json | null
          "record_count": number | null
          "ip": string | null
          "created_at": string
        }
        Insert: {
          "id"?: number
          "user_id"?: string | null
          "role"?: string | null
          "route": string
          "action": string
          "edition_id"?: string | null
          "filters"?: Json | null
          "record_count"?: number | null
          "ip"?: string | null
          "created_at"?: string
        }
        Update: {
          "id"?: number
          "user_id"?: string | null
          "role"?: string | null
          "route"?: string
          "action"?: string
          "edition_id"?: string | null
          "filters"?: Json | null
          "record_count"?: number | null
          "ip"?: string | null
          "created_at"?: string
        }
        Relationships: []
      }
      "banks": {
        Row: {
          "id": string
          "name": string
          "aliases": string[]
          "active": boolean
        }
        Insert: {
          "id": string
          "name": string
          "aliases"?: string[]
          "active"?: boolean
        }
        Update: {
          "id"?: string
          "name"?: string
          "aliases"?: string[]
          "active"?: boolean
        }
        Relationships: []
      }
      "categories": {
        Row: {
          "id": string
          "name": string
          "group_key": string
          "is_state_scoped": boolean
          "requires_sport": boolean
          "requires_committee": boolean
          "sort_order": number
          "active": boolean
        }
        Insert: {
          "id"?: string
          "name": string
          "group_key": string
          "is_state_scoped"?: boolean
          "requires_sport"?: boolean
          "requires_committee"?: boolean
          "sort_order"?: number
          "active"?: boolean
        }
        Update: {
          "id"?: string
          "name"?: string
          "group_key"?: string
          "is_state_scoped"?: boolean
          "requires_sport"?: boolean
          "requires_committee"?: boolean
          "sort_order"?: number
          "active"?: boolean
        }
        Relationships: []
      }
      "committees": {
        Row: {
          "id": string
          "name": string
          "edition_id": string | null
          "active": boolean
        }
        Insert: {
          "id"?: string
          "name": string
          "edition_id"?: string | null
          "active"?: boolean
        }
        Update: {
          "id"?: string
          "name"?: string
          "edition_id"?: string | null
          "active"?: boolean
        }
        Relationships: []
      }
      "duplicate_reviews": {
        Row: {
          "id": string
          "edition_id": string
          "participation_id": string
          "matched_person_id": string
          "matched_edition_id": string
          "match_type": string
          "similarity_score": number | null
          "is_blocking": boolean
          "status": string
          "resolved_by": string | null
          "resolved_at": string | null
          "resolution_note": string | null
          "created_at": string
        }
        Insert: {
          "id"?: string
          "edition_id": string
          "participation_id": string
          "matched_person_id": string
          "matched_edition_id": string
          "match_type": string
          "similarity_score"?: number | null
          "is_blocking"?: boolean
          "status"?: string
          "resolved_by"?: string | null
          "resolved_at"?: string | null
          "resolution_note"?: string | null
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "edition_id"?: string
          "participation_id"?: string
          "matched_person_id"?: string
          "matched_edition_id"?: string
          "match_type"?: string
          "similarity_score"?: number | null
          "is_blocking"?: boolean
          "status"?: string
          "resolved_by"?: string | null
          "resolved_at"?: string | null
          "resolution_note"?: string | null
          "created_at"?: string
        }
        Relationships: []
      }
      "editions": {
        Row: {
          "id": string
          "name": string
          "year": number
          "status": string
          "is_reference": boolean
          "starts_on": string | null
          "ends_on": string | null
          "created_at": string
          "closed_at": string | null
        }
        Insert: {
          "id"?: string
          "name": string
          "year": number
          "status"?: string
          "is_reference"?: boolean
          "starts_on"?: string | null
          "ends_on"?: string | null
          "created_at"?: string
          "closed_at"?: string | null
        }
        Update: {
          "id"?: string
          "name"?: string
          "year"?: number
          "status"?: string
          "is_reference"?: boolean
          "starts_on"?: string | null
          "ends_on"?: string | null
          "created_at"?: string
          "closed_at"?: string | null
        }
        Relationships: []
      }
      "import_runs": {
        Row: {
          "id": string
          "edition_id": string
          "kind": string
          "category_id": string | null
          "state_id": string | null
          "file_path": string
          "original_name": string
          "row_count": number
          "accepted_count": number
          "rejected_count": number
          "rejections": Json
          "status": string
          "uploaded_by": string
          "created_at": string
        }
        Insert: {
          "id"?: string
          "edition_id": string
          "kind": string
          "category_id"?: string | null
          "state_id"?: string | null
          "file_path": string
          "original_name": string
          "row_count"?: number
          "accepted_count"?: number
          "rejected_count"?: number
          "rejections"?: Json
          "status"?: string
          "uploaded_by": string
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "edition_id"?: string
          "kind"?: string
          "category_id"?: string | null
          "state_id"?: string | null
          "file_path"?: string
          "original_name"?: string
          "row_count"?: number
          "accepted_count"?: number
          "rejected_count"?: number
          "rejections"?: Json
          "status"?: string
          "uploaded_by"?: string
          "created_at"?: string
        }
        Relationships: []
      }
      "participations": {
        Row: {
          "id": string
          "edition_id": string
          "person_id": string
          "category_id": string
          "state_id": string | null
          "sport_id": string | null
          "committee_id": string | null
          "account_name": string | null
          "account_number": string | null
          "bank_id": string | null
          "pre_games_accredited": boolean
          "arrival_accredited": boolean
          "arrival_accredited_at": string | null
          "arrival_source": string | null
          "entitlement_amount": number | null
          "exclusion_reason": string | null
          "is_payable": boolean | null
          "source_import_id": string | null
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "edition_id": string
          "person_id": string
          "category_id": string
          "state_id"?: string | null
          "sport_id"?: string | null
          "committee_id"?: string | null
          "account_name"?: string | null
          "account_number"?: string | null
          "bank_id"?: string | null
          "pre_games_accredited"?: boolean
          "arrival_accredited"?: boolean
          "arrival_accredited_at"?: string | null
          "arrival_source"?: string | null
          "entitlement_amount"?: number | null
          "exclusion_reason"?: string | null
          "is_payable"?: boolean | null
          "source_import_id"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "edition_id"?: string
          "person_id"?: string
          "category_id"?: string
          "state_id"?: string | null
          "sport_id"?: string | null
          "committee_id"?: string | null
          "account_name"?: string | null
          "account_number"?: string | null
          "bank_id"?: string | null
          "pre_games_accredited"?: boolean
          "arrival_accredited"?: boolean
          "arrival_accredited_at"?: string | null
          "arrival_source"?: string | null
          "entitlement_amount"?: number | null
          "exclusion_reason"?: string | null
          "is_payable"?: boolean | null
          "source_import_id"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: []
      }
      "payment_batches": {
        Row: {
          "id": string
          "edition_id": string
          "reference": string
          "description": string | null
          "filter_json": Json
          "record_count": number
          "total_amount": number
          "status": string
          "generated_by": string
          "generated_at": string
        }
        Insert: {
          "id"?: string
          "edition_id": string
          "reference": string
          "description"?: string | null
          "filter_json": Json
          "record_count"?: number
          "total_amount"?: number
          "status"?: string
          "generated_by": string
          "generated_at"?: string
        }
        Update: {
          "id"?: string
          "edition_id"?: string
          "reference"?: string
          "description"?: string | null
          "filter_json"?: Json
          "record_count"?: number
          "total_amount"?: number
          "status"?: string
          "generated_by"?: string
          "generated_at"?: string
        }
        Relationships: []
      }
      "payments": {
        Row: {
          "id": string
          "batch_id": string
          "participation_id": string
          "amount": number
          "account_number": string
          "bank_id": string
          "status": string
          "partner_reference": string | null
          "failure_reason": string | null
          "paid_at": string | null
          "created_at": string
        }
        Insert: {
          "id"?: string
          "batch_id": string
          "participation_id": string
          "amount": number
          "account_number": string
          "bank_id": string
          "status"?: string
          "partner_reference"?: string | null
          "failure_reason"?: string | null
          "paid_at"?: string | null
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "batch_id"?: string
          "participation_id"?: string
          "amount"?: number
          "account_number"?: string
          "bank_id"?: string
          "status"?: string
          "partner_reference"?: string | null
          "failure_reason"?: string | null
          "paid_at"?: string | null
          "created_at"?: string
        }
        Relationships: []
      }
      "persons": {
        Row: {
          "id": string
          "bvn_encrypted": string | null
          "nin_encrypted": string | null
          "bvn_hash": string | null
          "nin_hash": string | null
          "full_name": string
          "normalised_name": string
          "phone": string | null
          "created_at": string
          "updated_at": string
        }
        Insert: {
          "id"?: string
          "bvn_encrypted"?: string | null
          "nin_encrypted"?: string | null
          "bvn_hash"?: string | null
          "nin_hash"?: string | null
          "full_name": string
          "normalised_name": string
          "phone"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Update: {
          "id"?: string
          "bvn_encrypted"?: string | null
          "nin_encrypted"?: string | null
          "bvn_hash"?: string | null
          "nin_hash"?: string | null
          "full_name"?: string
          "normalised_name"?: string
          "phone"?: string | null
          "created_at"?: string
          "updated_at"?: string
        }
        Relationships: []
      }
      "rates": {
        Row: {
          "id": string
          "edition_id": string
          "category_id": string
          "sport_id": string | null
          "amount": number
          "created_at": string
        }
        Insert: {
          "id"?: string
          "edition_id": string
          "category_id": string
          "sport_id"?: string | null
          "amount": number
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "edition_id"?: string
          "category_id"?: string
          "sport_id"?: string | null
          "amount"?: number
          "created_at"?: string
        }
        Relationships: []
      }
      "sports": {
        Row: {
          "id": string
          "name": string
          "active": boolean
        }
        Insert: {
          "id"?: string
          "name": string
          "active"?: boolean
        }
        Update: {
          "id"?: string
          "name"?: string
          "active"?: boolean
        }
        Relationships: []
      }
      "states": {
        Row: {
          "id": string
          "name": string
          "code": string
          "active": boolean
        }
        Insert: {
          "id"?: string
          "name": string
          "code": string
          "active"?: boolean
        }
        Update: {
          "id"?: string
          "name"?: string
          "code"?: string
          "active"?: boolean
        }
        Relationships: []
      }
      "user_category_access": {
        Row: {
          "user_id": string
          "category_id": string
        }
        Insert: {
          "user_id": string
          "category_id": string
        }
        Update: {
          "user_id"?: string
          "category_id"?: string
        }
        Relationships: []
      }
      "user_profiles": {
        Row: {
          "id": string
          "full_name": string
          "role": string
          "active": boolean
          "created_at": string
        }
        Insert: {
          "id": string
          "full_name": string
          "role": string
          "active"?: boolean
          "created_at"?: string
        }
        Update: {
          "id"?: string
          "full_name"?: string
          "role"?: string
          "active"?: boolean
          "created_at"?: string
        }
        Relationships: []
      }
      "user_state_access": {
        Row: {
          "user_id": string
          "state_id": string
        }
        Insert: {
          "user_id": string
          "state_id": string
        }
        Update: {
          "user_id"?: string
          "state_id"?: string
        }
        Relationships: []
      }
    }
    Views: {
      "participations_v": {
        Row: {
          "id": string | null
          "edition_id": string | null
          "person_id": string | null
          "category_id": string | null
          "state_id": string | null
          "sport_id": string | null
          "committee_id": string | null
          "account_name": string | null
          "account_number": string | null
          "bank_id": string | null
          "pre_games_accredited": boolean | null
          "arrival_accredited": boolean | null
          "arrival_accredited_at": string | null
          "arrival_source": string | null
          "entitlement_amount": number | null
          "exclusion_reason": string | null
          "is_payable": boolean | null
          "source_import_id": string | null
          "created_at": string | null
          "updated_at": string | null
          "full_name": string | null
          "normalised_name": string | null
          "phone": string | null
          "category_name": string | null
          "group_key": string | null
          "state_name": string | null
          "sport_name": string | null
          "committee_name": string | null
          "bank_name": string | null
          "amount_paid": number | null
          "balance": number | null
        }
        Relationships: []
      }
      "participations_viewer_v": {
        Row: {
          "id": string | null
          "edition_id": string | null
          "person_id": string | null
          "category_id": string | null
          "state_id": string | null
          "sport_id": string | null
          "committee_id": string | null
          "full_name": string | null
          "category_name": string | null
          "state_name": string | null
          "sport_name": string | null
          "bank_name": string | null
          "pre_games_accredited": boolean | null
          "arrival_accredited": boolean | null
          "is_payable": boolean | null
          "payment_status": string | null
        }
        Relationships: []
      }
    }
    Functions: {
      [key: string]: never
    }
    Enums: {
      [key: string]: never
    }
    CompositeTypes: {
      [key: string]: never
    }
  }
}
